{% set conda_name = "datadotworld-py" %}
{% set name = "datadotworld" %}
{% set version = "1.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "4d3c8a1306e05f08b46384cc0c4a86140ce1efab4e717cf363ead9f18824de72" %}
{% set build = 0 %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  entry_points:
    - dw = datadotworld.cli:cli

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner >=2.11,<3.0a

  run:
    - python
    - certifi >=2017.04.17
    - click >=6.0,<7.0a
    - configparser >=3.5.0,<4.0a  # [py<34]
    - datapackage-py >=0.8.8,<1.0a
    - jsontableschema >=0.10.0,<1.0a
    - python-dateutil >=2.6.0,<3.0a
    - requests >=2.0.0,<3.0a
    - six >=1.5.0,<2.0a
    - tabulator-py <2.0a
    - urllib3 >=1.15,<2.0a
    - pandas <1.0a

test:
  imports:
    - datadotworld
    - datadotworld.client
    - datadotworld.client._swagger
    - datadotworld.client._swagger.apis
    - datadotworld.client._swagger.models
    - datadotworld.models

  commands:
    - dw --help

about:
  home: http://github.com/datadotworld/data.world-py
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Python library for data.world'
  dev_url: http://github.com/datadotworld/data.world-py
  doc_url: https://github.com/datadotworld/data.world-py

extra:
  recipe-maintainers:
    - pmlandwehr
