travis:
  secure:
    BINSTAR_TOKEN: MreFsG1gay0149PYm8SO77dRlRwA2j1UWCJTx9r66rIGme2G1/8Qi2C9ztYC2g9BzssYxc3cqJOEI/6MLUhFlfr4R7GoDwx+5t2kuli626I92mVWT2cvpQ3MNk2vjrAHaxQ2i1Q/fF6k/dPTclzqif+ALNefPaAjYKGGtj3ys0e/9hfDXw9Ec7rs1E7+pDOlATOb6O6F6qOebWLHzx/rExiUmsApWnqZp0CEcfPkqMLsNqYtRpmb9094DWmlMYTEczmxzdU1LM3R80aAL6jdumdwES1CNXtnMU1wrdspYtYC/wQqpR2gligSAk67P8R64tyxSXNW1Qx3oLSF5Q25DV4GgtzGU2/BeYjHPgwQiVKRhdT4THF5XMIkWux8GvkK5aWXA8zOwQQxulG4vjCaw5JPOxQQdM8u64nOt0phRAyeEgtpaxRdidl6gkvqZm2QcDacgbznYbXpHNcMjW+pHO1r0XkAtoT+0UmHC1izqDMX7hni8mMqo/4SPqi4qBnVniMbrYd7w7hNGiW1GS3GXdV0gtPZxtSW1lUXXO0gGQv0CQxr73611jGdkM6LFLvRTxMs7AdEJs4aA/c1/wx564MxAXp+dRSIQE/bBRMTax40PCwUxlzasKQiAmB7XcBF8TzL+9gP9O6NqJfogJ3Pw71liU1zJs0vNuhns1WtgVE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
