travis:
  secure:
    BINSTAR_TOKEN: DaaxCTeldl0ktIVmdt4b/gu5r0Xi8A7EzOTV0En7tXimv2IsUbwRagGOSNhz27LSnIlXqIGhPiq5Js2XpIbMZdgQMkwU7avvkak7udtGVIm7+ESrTztz+E8k/Xs9+tZcgOh7KPUw9KOyesj/eBm2SbZ0VL/qUFxHTqqzwXZnR3/8R3BQ8Kmc9sSQF8+Vk27VhX+CwDJxmGd8KKwPwiHHqclsbZ0K1UNHHqSCRdur7QJpXEqub0oxwzaIK2k4EG/ftFBQIxSyf9ORsEYSVBvr/w7vSrQMzTwGS2xc4aHeymmifVPWG23r/ufGGY3jTTI9Jz+HBs63OGfOHAsXVD6JLane/DYxevFUkTYHNw0wgsvpN9U3MAQYu7yMGxAUd+eYHIpLNsDHlYwPKRerqrCEgYXd/5LA4SuWjdLq3KEOEB/0IVRMRRp9hrfIycf5BbwlMRCEfXGxtOEfpfVXqu1jR6X21BniBPd2OM8lFZa6pT3tFNz1R3QZl4kiwN9Ylk4EDQM1H07+UASO9cKwtmunEbCmKGTJezd7ZVgMlKPqaJmVmEhMpV8hns3dpsIMeUPqRsADnneN61eFkcV9cCJ/TuBsjpY9NVez8bSGpClFtmdO9z7BkyXUVXdtlYIoWxhwydnonijfB2b4zxwgjp/TAgQh3nzYajJY3HcLEKFvKxU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
